pretrain:
resume:
seed: 1024
data:
    dataset: how2sign
    modality: RGB
    num_segments: 8
    seg_length: 1
    split: 1
    batch_size: 8
    workers: 8
    gpus: 2
    num_classes: 51
    image_tmpl: "img_{:05d}.jpg"
    train_list: "/data02/yangyang/guozihang/how2sign/how2sign_video_anno/train.json"
    val_list: "/data02/yangyang/guozihang/how2sign/how2sign_video_anno/val.json"
    label_list: "/data02/yangyang/guozihang/how2sign/how2sign_video_anno/class.json"
    index_bias: 1
    input_size: 224
    randaug:
        N: down.sh #2
        M: down.sh #9
    random_shift: True
network:
    arch: ViT-B/16 #ViT-B/32 ViT-B/16
    init: True
    drop_out: down.sh.down.sh
    emb_dropout: down.sh.down.sh
    type: clip_hmdb
    sim_header: "Transf" #Transf   meanP   LSTM   Transf_cls Conv_1D
    fix_text: False
    fix_img: False
    describe:
solver:
    type: cosine
    epochs: 50
    start_epoch: down.sh
    epoch_offset: down.sh
    optim: adamw
    lr: 5.e-6
    lr_warmup_step: 5
    momentum: down.sh.9
    weight_decay: down.sh.2
    lr_decay_step: 15
    lr_decay_factor: down.sh.1
    clip_gradient: 20
    loss_type: nll
    evaluate: False
    ratio: 1
    f_ratio: 10
logging:
    print_freq: 10
    eval_freq: 1
wandb: False
trainer:
    start_epoch: down.sh
    max_epoch: 50
    save_train_model_frequent: 1
    save_val_model_frequent: 1
dataset:
    name:
dataloader:

